### ISSUE TITLE
Can not see my companions' locations on the map

### ISSUE THREAD

**Issue by ReinierAarnink1996** [davidvorona/gim-plugin#13]
Good day,

Thanks for making the plugin.
I have a server on amazon aws, lightsail. I did connect to it using their browser-based SSH client.
Then I followed your other instructions.
git clone repository
cd gimp-server
npm install
npm start

it does say its listening on 3000. I have entered a static ip and the non-static ip. But still, I can not see my companions' locations when im on osrs. On osrs I click the minimap, im in the same world, I know where my alt is. 

this is where my files are (not sure how to remove the line that crosses threw the text,  swapped server ip for 999-99-9-999:):
bitnami@ip-999-99-9-999:~$ ls
bitnami_application_password  bitnami_credentials  gimp-server  htdocs  package-lock.json  stack
bitnami@ip-999-99-9-999::~$ cd gimp-server
bitnami@ip-999-99-9-999::~/gimp-server$ ls
gimp.js  package.json  package-lock.json  README.md  server.js

What am I doing wrong?
my discord: Esq Reinier | Draspula#3685

**Comment by davidvorona** [comment]
Just in case it wasn't clear, this only works with group ironmen, so your alt would *have* to be in the same GIM group as your other account.

This is partly my fault, I'm in the middle of a giant refactor and ended up changing the server code a bit. It probably doesn't work properly with the current plugin that's on the plugin hub. Revert the server code to this commit: https://github.com/davidvorona/gimp-server/tree/8bba493c21ce867bbaced5bf0c972a7506457902 and it should work properly. You can use this command:

```
git reset --hard 8bba493c21ce867bbaced5bf0c972a7506457902
```

**Comment by ReinierAarnink1996** [comment]
> Just in case it wasn't clear, this only works with group ironmen, so your alt would _have_ to be in the same GIM group as your other account.
> 
> This is partly my fault, I'm in the middle of a giant refactor and ended up changing the server code a bit. It probably doesn't work properly with the current plugin that's on the plugin hub. Revert the server code to this commit: https://github.com/davidvorona/gimp-server/tree/8bba493c21ce867bbaced5bf0c972a7506457902 and it should work properly. You can use this command:
> 
> ```
> git reset --hard 8bba493c21ce867bbaced5bf0c972a7506457902
> ```
I did:
cd gimp-server
git reset --hard 8bba493c21ce867bbaced5bf0c972a7506457902
npm install
npm start

tells me its running on port 3000 like last time
I test it, and it does not work..

Then I did cat server.js and I could not find const Gimp = require("./gimp"); which means the server.js did update correctly.. so I dont know whats wrong.

here are screenshots of my lightsail management screen, I thought maybe there is something wrong on my side so I thought maybe IPv6 firewall rules should be deleted but what do I know..:
http://prntscr.com/26c6938
http://prntscr.com/26c697v

**Comment by davidvorona** [comment]
I assume both ironmen are being played on Runelite, both with the GIMP plugin and both with the same IP/port settings. I'm sure that's obvious but just want to be sure.

Depending on your hosting service and its configuration the issue could be the port. Load balancing, proxies, and firewalls can cause issues. Is there an explicit externalized port for HTTP for the instance you're running?

If you wanted to confirm it's an issue with connecting to your AWS instance, I would run it locally on the same machine you're running Runelite, and set the IP to your machine's IP and the port to 3000.

Sorry for these issues.

**Comment by davidvorona** [comment]
Try changing the port in the code to 80, which seems to be the port rule for HTTP in your firewall settings. Then change the port in the plugin config to 80 as well.

**Comment by ReinierAarnink1996** [comment]
> 

I did vim server.js
pressed i to enter insert mode
changed the port from 3000 to 80
unfortunately it cant connect with that port
changing the port did not work

**Comment by ReinierAarnink1996** [comment]
> Try changing the port in the code to 80, which seems to be the port rule for HTTP in your firewall settings. Then change the port in the plugin config to 80 as well.

**Comment by davidvorona** [comment]
I'm surprised the port thing didn't work, honestly. I assume the server was restarted after changing the port?

I've been toying with the idea of running my own public server that people can use so they don't have to set up something themselves. Would cost me $$ and take some time to refactor the server to handle it but I could just go real cheap and make sure people know that performance might be less than ideal.

I'll start testing it and see if I can figure out your issue in the process. Worst case scenario, you can be the first one to use the public server once its out.

**Comment by ReinierAarnink1996** [comment]
Is it working for you actually?

> Just in case it wasn't clear, this only works with group ironmen, so your alt would _have_ to be in the same GIM group as your other account.
> 
> This is partly my fault, I'm in the middle of a giant refactor and ended up changing the server code a bit. It probably doesn't work properly with the current plugin that's on the plugin hub. Revert the server code to this commit: https://github.com/davidvorona/gimp-server/tree/8bba493c21ce867bbaced5bf0c972a7506457902 and it should work properly. You can use this command:
> 
> ```
> git reset --hard 8bba493c21ce867bbaced5bf0c972a7506457902
> ```

Could you test if the plugin is working correctly for you with this version. Because if it works for you, it must be a problem with my hosting service and not your code. Will also try to run it locally anyway.

**Comment by davidvorona** [comment]
Yup, just connected to my own server at that commit. Seems to be working fine.

**Comment by ReinierAarnink1996** [comment]
> Yup, just connected to my own server at that commit. Seems to be working fine.
Just tried running it locally. This time it says:
Listening on *:3000
Client connected: iK14xImhKJtmNLbOAAAB
Client connected: 3ip-6sYdhdVeoo0UAAAD

I did not get client connected last time, so thats good. But still, I do not see the other group ironman on the minimap. I entered port 3000 in the plugin settings on both clients and the same ipv4 address (the ipv4 address of my computer). What am I doing wrong...?

http://prntscr.com/26cvuoi
http://prntscr.com/26cvv91

**Comment by davidvorona** [comment]
The reconnect behavior when your config changes is not very good in that version. It *could* be you just have to restart RuneLite on both clients now that you have a working server IP and port entered into the settings. Does restarting and re-logging in fix it?

**Comment by davidvorona** [comment]
FYI, you won't see your own icon on the map, only others. But you've got two accounts so that's definitely not the problem.

**Comment by davidvorona** [comment]
Oh, looking at your server code it seems like that's the new server. Revert back to the commit I mentioned earlier.

**Comment by ReinierAarnink1996** [comment]
> Oh, looking at your server code it seems like that's the new server. Revert back to the commit I mentioned earlier.

http://prntscr.com/26cwm2h

**Comment by ReinierAarnink1996** [comment]
Guess what? Got it up and running threw amazon 👯‍♂️ 

This video helped me solved the problem.
https://www.youtube.com/watch?v=s8GuMPwf46g&t=0s
24:55 - 27:45
Basically, the port in the server.js is 3000
so I had to "Add rule" to the IPv4/IPv6 Firewall, enter port 3000, protocol TCP (because its http) and application custom.
http://prntscr.com/26cx9fr

The video also thought me the command forever start server.js
After closing the web interface, the GIM plugin didn't work anymore. So this command is also a must (video explains this at 22:00-23:05). It is also needed to use a static ip.

**Comment by davidvorona** [comment]
`forever` is a good tool for running continuous node scripts. If you have the time to set it up, `pm2` is even better (it's what I use for the server I run).

The port rule makes sense, should've thought of that. In the release coming up, you should not have to do that anymore, as I will have the application port default to the environment port, which is probably supported automatically by Lightsail.

Sorry about all the issues. Next version is gonna be much better, with tons of new features :)

**Comment by ReinierAarnink1996** [comment]
Was a fun learning experience aswell tbh, cheers
