### ISSUE TITLE
I can't see my friends but they can see me

### ISSUE THREAD

**Issue by samanthar0se** [davidvorona/gim-plugin#38]
![image](https://user-images.githubusercontent.com/47303858/157553880-4778242c-9d35-43c6-8b52-2e3c4853d968.png)

**Comment by davidvorona** [comment]
I do not see the user "ScarOverflow" in the OSRS Hiscores (which this plugin uses to display stats). New accounts or accounts with low levels will having missing skills or sometimes not show up at all until they've increased their skills a bit.

If you look up a username [here](https://secure.runescape.com/m=hiscore_oldschool/overall) and they show up but they're still not showing up in the plugin panel, let me know and I will look into it.

**Comment by samanthar0se** [comment]
We are all new accounts, I should have been more specific that I cannot see them on the minimap but they can see each other. All our accounts are new from today.

**Comment by davidvorona** [comment]
Make sure you're all in the overworld to test if you can see each other, like test outside Lumbridge Castle or at the GE or something. If you're underground or on the 2nd floor of a building they'll have to click to that plane via the dropdown menu at the bottom of the map and find you.

If it's still not working, make sure your address is correct and matches theirs; if you're using the public server: https://gimp-server.herokuapp.com is the address.

**Comment by samanthar0se** [comment]
We are all on the overworld, and we did verify that we’re all pointing at
the correct address. The only obvious difference between us, to my eyes, is
that my name has a space in it and theirs do not. I was going to try to
spin up a local server instance tomorrow to see if that helped.

**Comment by davidvorona** [comment]
Hmm I will look into this tomorrow, space in the name could be an issue.

**Comment by davidvorona** [comment]
Can confirm the client has an issue with spaces in names, I will work on this and try to get a fix out this weekend.
