### ISSUE TITLE
Could we get a total skill level added to the display like the HiScore display?

### ISSUE THREAD

**Issue by swirle13** [davidvorona/gim-plugin#60]
Pretty straightforward request. I'm hoping to have a total level segment added to the group ironman stats, similar to how the HiScore plugin displays this.

There was a commit added to the HiScore plugin to address the issue when a level is below 10 and can't be seen via the hiscores: https://github.com/runelite/runelite/issues/4691#issuecomment-445079703

> Fixed in https://github.com/runelite/runelite/commit/233fbcf2d1c28cf458953df45e31ecf271d794a7 by showing stats the jagex hiscore api returns as unranked but has level/xp for.

**Comment by davidvorona** [comment]
Yeah I should be able to add this pretty easily, I'll try and submit the update to RL by the end of the week and I'll link the PR here so you can track it.

**Comment by davidvorona** [comment]
It was pretty quick: https://github.com/runelite/plugin-hub/pull/5492

Will take them anywhere from a day to two weeks to approve.

**Comment by swirle13** [comment]
Merged into runelite via https://github.com/runelite/plugin-hub/pull/5492
