### ISSUE TITLE
Missing New Varlamore Pt 2 Bosses

### ISSUE THREAD

**Issue by swirle13** [davidvorona/gim-plugin#65]
Missing Amoxliatl, The Hueycoatl, and Araxxor

![image](https://github.com/user-attachments/assets/3317215a-e510-4918-acc3-653747738c6a)
![image](https://github.com/user-attachments/assets/7706ebf8-3d7b-43ba-9582-b9734b51aa0f)
![image](https://github.com/user-attachments/assets/d22d533f-544c-4fc5-9265-bf57ce7027e7)

**Comment by davidvorona** [comment]
Sorry for the delay, I've just PR'd to the plugin hub repo so these bosses will be available once RuneLite has approved and merged the update. You can follow it here: https://github.com/runelite/plugin-hub/pull/6787
